# Generated by Django 3.1 on 2020-10-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=200)),
                ('shop_website_link', models.CharField(max_length=500)),
                ('shop_image', models.ImageField(default='shop_images/default_shop_image.jpg', upload_to='shop_images')),
            ],
        ),
    ]
