# Generated by Django 3.1 on 2020-10-29 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.city'),
        ),
    ]
