# Generated by Django 3.1 on 2020-10-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_shop_shop_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='clik_n_collect',
            field=models.BooleanField(default=False),
        ),
    ]
