# Generated by Django 3.1 on 2020-10-31 09:19

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201031_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
