# Generated by Django 3.1.2 on 2020-10-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20201031_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_website_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
