# Generated by Django 3.1.2 on 2020-11-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20201031_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
