# Generated by Django 3.1.2 on 2020-11-01 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_shop_validated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='adress',
            new_name='address',
        ),
    ]
