# Generated by Django 3.1.2 on 2020-11-01 09:29

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20201101_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse mail'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='how_to_order',
            field=models.TextField(blank=True, null=True, verbose_name='Comment commander chez vous ?'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.city', verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_image',
            field=models.ImageField(default='shop_images/default_shop_image.jpg', upload_to='shop_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=200, verbose_name='Nome du commerce'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_website_link',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien de votre site (facultatif)'),
        ),
    ]
