# Generated by Django 3.1.2 on 2020-11-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20201101_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=200, verbose_name='Nom du commerce'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_website_link',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien du site web'),
        ),
    ]
