# Generated by Django 3.1.2 on 2020-11-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20201101_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='clik_n_collect',
        ),
        migrations.AlterField(
            model_name='shop',
            name='how_to_order',
            field=models.TextField(null=True, verbose_name='Comment commander chez vous ?'),
        ),
    ]
